import { useCallback,useEffect,useMemo,useState } from 'react'
import type { ReactNode } from 'react'
import { Activity,AlertTriangle,CalendarClock,Flag,Gauge,Radio,RefreshCw,Trophy,Wifi,WifiOff } from 'lucide-react'
import type { ChampionshipProjection,CompetitionState,ConnectionState,DriverTiming,RaceWeekend,SessionState,StandingEntry,View } from './types'
import { attachGrid,competitionFromSession,selectCurrentEvent,selectNextEvent } from './data/lifecycle'
import { projectConstructors,projectDriverStandings } from './data/scoring'
import { emptySession,F1ArchiveSource,F1SignalRSource,JolpicaDataSource } from './data/sources'

const liveSource=new F1SignalRSource(),archiveSource=new F1ArchiveSource(),dataSource=new JolpicaDataSource()

export default function App(){
  const [view,setView]=useState<View>('qualifying'),[session,setSession]=useState<SessionState>(emptySession()),[connection,setConnection]=useState<ConnectionState>({mode:'CONNECTING',attempt:0,message:'実データを確認中'})
  const [schedule,setSchedule]=useState<RaceWeekend[]>([]),[driverBase,setDriverBase]=useState<StandingEntry[]>([]),[constructorBase,setConstructorBase]=useState<StandingEntry[]>([]),[archive,setArchive]=useState<SessionState>(),[grid,setGrid]=useState<Record<string,number>>({}),[scheduleError,setScheduleError]=useState(false),[reconnectKey,setReconnectKey]=useState(0),[dataRefreshKey,setDataRefreshKey]=useState(0),[isRefreshing,setIsRefreshing]=useState(false),[lastUpdatedAt,setLastUpdatedAt]=useState<string>()
  const currentEvent=selectCurrentEvent(schedule,session),competition=competitionFromSession(session,currentEvent),nextEvent=selectNextEvent(schedule)

  useEffect(()=>{let active=true,finishTimer:number|undefined;const season=new Date().getFullYear(),started=Date.now();setScheduleError(false);Promise.allSettled([dataSource.getSeasonSchedule(season),dataSource.getDriverStandings(season),dataSource.getConstructorStandings(season)]).then(([s,d,c])=>{if(!active)return;const succeeded=s.status==='fulfilled'||d.status==='fulfilled'||c.status==='fulfilled';if(s.status==='fulfilled')setSchedule(s.value);else setScheduleError(true);if(d.status==='fulfilled')setDriverBase(d.value);if(c.status==='fulfilled')setConstructorBase(c.value);const finish=()=>{if(!active)return;if(succeeded)setLastUpdatedAt(new Date().toISOString());setIsRefreshing(false)};finishTimer=window.setTimeout(finish,Math.max(0,650-(Date.now()-started)))});return()=>{active=false;if(finishTimer)window.clearTimeout(finishTimer)}},[dataRefreshKey])
  useEffect(()=>{let stop:(()=>void)|undefined,active=true;liveSource.connect(s=>{if(active){setSession(s);setLastUpdatedAt(s.updatedAt||new Date().toISOString())}},c=>{if(active){setConnection(c);if(c.lastUpdate)setLastUpdatedAt(c.lastUpdate)}}).then(fn=>stop=fn);return()=>{active=false;stop?.()}},[reconnectKey])
  useEffect(()=>{if(competition!=='RACE'||!currentEvent)return;let active=true;Promise.all([archiveSource.loadQualifying(currentEvent),archiveSource.loadGrid(currentEvent)]).then(([q,g])=>{if(active){setArchive(q);setGrid(g)}}).catch(()=>{});return()=>{active=false}},[competition,currentEvent?.round])

  const reconnect=useCallback(()=>{if(isRefreshing)return;setIsRefreshing(true);setConnection({mode:'CONNECTING',attempt:0,message:'実データを再取得中'});setDataRefreshKey(k=>k+1);setReconnectKey(k=>k+1)},[isRefreshing])
  const qualifyingForRace=useMemo(()=>archive?attachGrid(archive,grid):undefined,[archive,grid])
  const projectedDrivers=useMemo(()=>competition==='RACE'?projectDriverStandings(driverBase,session.drivers):asConfirmed(driverBase),[competition,driverBase,session.drivers])
  const projectedTeams=useMemo(()=>competition==='RACE'?projectConstructors(constructorBase,projectedDrivers):asConfirmed(constructorBase),[competition,constructorBase,projectedDrivers])
  const event=currentEvent??nextEvent

  return <div className="app-shell"><Header event={event} session={session} competition={competition} connection={connection}/>
    <nav className="view-tabs" aria-label="画面切り替え"><Tab active={view==='qualifying'} onClick={()=>setView('qualifying')} icon={<Gauge/>}>予選</Tab><Tab active={view==='race'} onClick={()=>setView('race')} icon={<Flag/>}>決勝</Tab><Tab active={view==='championship'} onClick={()=>setView('championship')} icon={<Trophy/>}>チャンピオンシップ</Tab><div className="tab-actions"><span className="last-updated">最終更新 {lastUpdatedAt?timeLabel(lastUpdatedAt):'取得中'}</span><button onClick={reconnect} disabled={isRefreshing} aria-busy={isRefreshing}><RefreshCw className={isRefreshing?'spinning':''}/><span className="action-label">{isRefreshing?'データを再取得中…':'データを再取得'}</span></button></div></nav>
    <main>{scheduleError&&<div className="api-notice"><AlertTriangle/>日程を取得できません。再接続してください。</div>}
      {view==='qualifying'&&(competition==='QUALIFYING'?<QualifyingView session={session}/>:competition==='RACE'?(qualifyingForRace?<QualifyingView session={qualifyingForRace} gridMode/>:<LoadingArchive/>):<IdleView event={nextEvent} lastUpdatedAt={lastUpdatedAt}/>) }
      {view==='race'&&(competition==='RACE'?<RaceView session={session}/>:competition==='QUALIFYING'?<GridPending event={currentEvent}/>:<IdleView event={nextEvent} lastUpdatedAt={lastUpdatedAt}/>) }
      {view==='championship'&&<ChampionshipView drivers={projectedDrivers} teams={projectedTeams} live={competition==='RACE'}/>} 
    </main><footer><span>UNOFFICIAL F1 DATA DASHBOARD</span><span>Data: Formula 1 Live Timing · Jolpica F1</span><span>非公式・個人利用 / 表示は暫定情報です</span></footer></div>
}

function Header({event,session,competition,connection}:{event?:RaceWeekend;session:SessionState;competition:CompetitionState;connection:ConnectionState}){return <header className="topbar"><div className="brand"><span className="brand-mark"><i/><i/><i/></span><div><b>PITWALL</b><small>LIVE TIMING · CREATED BY CHIKA</small></div></div><div className="event-title"><small>{event?`ROUND ${String(event.round).padStart(2,'0')} · ${event.season}`:'SEASON SCHEDULE'}</small><strong>{event?.meetingName??'次回大会を取得中'}</strong><span>{event?`${event.circuit} · ${event.locality}`:'Jolpica F1に接続しています'}</span></div><div className="session-clock"><span className={`flag flag-${session.flag.toLowerCase()}`}>{competition==='IDLE'?'STANDBY':session.flag}</span><div><small>{competition==='IDLE'?'次回予選':session.sessionName}</small><b>{competition==='RACE'?`LAP ${session.lap} / ${session.totalLaps}`:competition==='QUALIFYING'?session.timeRemaining:event?dateTime(event.qualifyingStart,'Asia/Tokyo'):'—'}</b></div></div><ConnectionBadge connection={connection} competition={competition}/></header>}
function ConnectionBadge({connection,competition}:{connection:ConnectionState;competition:CompetitionState}){const live=connection.mode==='LIVE'&&competition!=='IDLE';return <div className={`connection ${live?'live':'offline'}`}>{live?<Wifi/>:<WifiOff/>}<span><b>{live?'LIVE':'STANDBY'}</b><small>{live?'実セッション受信中':'ライブセッション待機中'}</small></span></div>}
function Tab({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:ReactNode;children:ReactNode}){return <button className={active?'active':''} onClick={onClick}>{icon}{children}</button>}

function IdleView({event,lastUpdatedAt}:{event?:RaceWeekend;lastUpdatedAt?:string}){const[,tick]=useState(0);useEffect(()=>{const id=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(id)},[]);return <section className="empty-state"><div className="empty-orbit"><CalendarClock/></div><small>NO ACTIVE QUALIFYING OR RACE SESSION</small><h1>現在は予選・決勝ともに<br/>競技中ではありません</h1>{event?<><p>次のグランプリ</p><h2>{event.meetingName}</h2><div className="next-session-grid"><div><small>日本時間</small><b>{dateTime(event.qualifyingStart,'Asia/Tokyo')}</b></div><div><small>開催地時間 · {event.locality}</small><b>{dateTime(event.qualifyingStart,event.timeZone)}</b></div><div><small>予選開始まで</small><b>{countdown(event.qualifyingStart)}</b></div></div></>:<p>次回予選の日程を取得しています。</p>}<span className="idle-last-updated">最終更新 {lastUpdatedAt?timeLabel(lastUpdatedAt):'取得中'}</span></section>}
function GridPending({event}:{event?:RaceWeekend}){return <section className="empty-state compact"><div className="empty-orbit warning"><Flag/></div><small>QUALIFYING IN PROGRESS</small><h1>決勝グリッドは<br/>まだ決定していません</h1><p>{event?.meetingName??'現在の大会'}の予選終了後も、ペナルティなどにより正式グリッドが変更される場合があります。</p></section>}
function LoadingArchive(){return <section className="empty-state compact"><div className="empty-orbit"><Radio/></div><small>QUALIFYING ARCHIVE</small><h1>Q3終了時の実データを<br/>読み込んでいます</h1></section>}

function QualifyingView({session,gridMode=false}:{session:SessionState;gridMode?:boolean}){return <section className="page-view"><SectionHeader eyebrow={gridMode?'QUALIFYING RESULT / CONFIRMED GRID':'LIVE QUALIFYING CLASSIFICATION'} title={gridMode?'予選結果と確定グリッド':'予選タイミング'} meta={`${session.drivers.length} DRIVERS · ${gridMode?'ARCHIVE':'LIVE'}`}/>{gridMode&&<div className="projection-note"><Activity/><div><b>Q3終了時の予選結果</b><span>確定グリッドとの差を併記しています。降格理由を取得できない場合は「確定グリッド変更」と表示します。</span></div><span className="provisional">確定グリッド</span></div>}<div className="table-wrap"><table className="timing-table qualifying-table"><thead><tr><th>{gridMode?'予選':'POS'}</th>{gridMode&&<th>GRID</th>}<th>DRIVER</th><th>TEAM</th><th>BEST</th><th>GAP</th><th>S1</th><th>S2</th><th>S3</th><th>{gridMode?'変更':'TYRE'}</th><th>STATUS</th></tr></thead><tbody>{session.drivers.map(d=><tr key={d.number} className={d.position===1?'leader':''}><td className="position">{d.position}</td>{gridMode&&<td className="position">{d.gridPosition<99?d.gridPosition:'—'}</td>}<td><DriverCell d={d}/></td><td className="team-name">{d.team}</td><td className="best">{d.bestLap}</td><td>{d.gap}</td>{d.sectors.map((s,i)=><td key={i}><span className={`sector ${s.status}`}>{s.value}</span></td>)}<td>{gridMode?<GridChange d={d}/>:<Tyre d={d}/>}</td><td><Status d={d}/></td></tr>)}</tbody></table></div></section>}
function RaceView({session}:{session:SessionState}){return <section className="page-view"><SectionHeader eyebrow="LIVE RACE CLASSIFICATION" title="グランプリ順位" meta={`LAP ${session.lap||'—'} / ${session.totalLaps||'—'}`}/><div className="race-summary"><div><small>RACE LEADER</small><b>{session.drivers[0]?.code??'—'}</b><span>{session.drivers[0]?.fullName??'未取得'}</span></div><div><small>TRACK STATUS</small><b className="green-text">{session.flag}</b><span>実タイミングデータ</span></div><div><small>LAPS REMAINING</small><b>{session.totalLaps?Math.max(0,session.totalLaps-session.lap):'—'}</b><span>推定値なし</span></div><div><small>SESSION STATUS</small><b>{session.status}</b><span>{timeLabel(session.updatedAt)}</span></div></div><div className="table-wrap"><table className="timing-table race-table"><thead><tr><th>POS</th><th>±</th><th>DRIVER</th><th>TEAM</th><th>INTERVAL</th><th>LEADER</th><th>LAST LAP</th><th>TYRE</th><th>PITS</th><th>STATUS</th></tr></thead><tbody>{session.drivers.map(d=><tr key={d.number}><td className="position">{d.position}</td><td><PositionDelta current={d.position} previous={d.gridPosition}/></td><td><DriverCell d={d}/></td><td className="team-name">{d.team}</td><td className="best">{d.interval}</td><td>{d.gap}</td><td>{d.lastLap}</td><td><Tyre d={d}/></td><td>{d.pitStops}</td><td><Status d={d}/></td></tr>)}</tbody></table></div></section>}

function ChampionshipView({drivers,teams,live}:{drivers:ChampionshipProjection[];teams:ChampionshipProjection[];live:boolean}){const[tab,setTab]=useState<'drivers'|'teams'>('drivers'),rows=tab==='drivers'?drivers:teams;return <section className="page-view championship-view"><SectionHeader eyebrow={live?'PROJECTED AFTER THIS RACE':'LATEST CONFIRMED STANDINGS'} title={live?'暫定チャンピオンシップ':'チャンピオンシップ'} meta={live?'LIVE PROJECTION':'CONFIRMED'}/>{live&&<div className="projection-note"><Activity/><div><b>現在の走行順位からライブ計算</b><span>正式結果確定前の暫定順位です。</span></div><span className="provisional">暫定</span></div>}<div className="champ-tabs"><button className={tab==='drivers'?'active':''} onClick={()=>setTab('drivers')}>ドライバー</button><button className={tab==='teams'?'active':''} onClick={()=>setTab('teams')}>コンストラクター</button></div>{rows.length?<div className="standings-list">{rows.map((r,i)=><StandingRow key={r.id} row={r} leader={rows[0]?.points||1} index={i} live={live}/>)}</div>:<div className="standings-empty">順位データを取得中です</div>}</section>}
function StandingRow({row,leader,index,live}:{row:ChampionshipProjection;leader:number;index:number;live:boolean}){return <div className={`standing-row ${index===0?'leader':''}`}><b className="rank">{row.position}</b><PositionDelta current={row.position} previous={row.previousPosition}/><i className="team-stripe" style={{background:row.color}}/><div className="standing-name"><b>{row.code}</b><span>{row.name}</span><small>{row.team}</small></div><div className="points-bar"><span style={{width:`${Math.max(6,row.points/leader*100)}%`,background:row.color}}/></div><div className="gain">{live?`+${row.projectedGain}`:'—'}<small>{live?'見込':'確定'}</small></div><strong className="total-points">{row.points}<small>PTS</small></strong></div>}

function SectionHeader({eyebrow,title,meta}:{eyebrow:string;title:string;meta:string}){return <div className="section-head"><div><small>{eyebrow}</small><h1>{title}</h1></div><span>{meta}</span></div>}
function DriverCell({d}:{d:DriverTiming}){return <div className="driver-cell"><i style={{background:d.teamColor}}/><b>{d.code}</b><span>{d.fullName}</span><small>#{d.number}</small></div>}
function GridChange({d}:{d:DriverTiming}){const n=d.gridChange??0;return <span className={`grid-change ${n>0?'down':n<0?'up':'same'}`}>{n>0?`▼ ${n}`:n<0?`▲ ${Math.abs(n)}`:'—'}<small>{d.penaltyReason}</small></span>}
function PositionDelta({current,previous}:{current:number;previous:number}){const n=previous-current;return <span className={`delta ${n>0?'up':n<0?'down':'same'}`}>{n>0?'▲':n<0?'▼':'—'} {n?Math.abs(n):''}</span>}
function Tyre({d}:{d:DriverTiming}){return <span className="tyre"><i className={d.tyre.compound.toLowerCase()}>{d.tyre.compound[0]}</i>{d.tyre.laps}L</span>}
function Status({d}:{d:DriverTiming}){return <span className={`driver-status ${d.status.toLowerCase()}`}>{d.status}</span>}
function asConfirmed(rows:StandingEntry[]):ChampionshipProjection[]{return rows.map((r,i)=>({...r,position:i+1,previousPosition:i+1,projectedGain:0}))}
function dateTime(value:string,zone:string){return new Intl.DateTimeFormat('ja-JP',{timeZone:zone,month:'short',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function countdown(value:string){const ms=new Date(value).getTime()-Date.now();if(ms<=0)return'まもなく開始';const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return`${d}日 ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function timeLabel(v?:string){if(!v)return'—';return new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v))}
