import { useEffect,useState } from 'react'
import type { RaceWeekend,SessionState,View,WeekendSession } from './types'
export function ScheduleView({schedule,currentEvent,session,onSelectSession}:{schedule:RaceWeekend[];currentEvent?:RaceWeekend;session:SessionState;onSelectSession:(view:View)=>void}) {
  const [selected,setSelected]=useState<string>(),[now,setNow]=useState(Date.now())
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[])
  const key=(event:RaceWeekend)=>`${event.season}-${event.round}`
  const event=schedule.find(e=>key(e)===selected)??currentEvent??schedule.find(e=>Date.parse(e.raceStart)>now)??schedule[0]
  const rows:WeekendSession[]=event?.sessions??(event?[{name:'予選',start:event.qualifyingStart,kind:'qualifying'},{name:'決勝',start:event.raceStart,kind:'race'}]:[])
  const names:Record<string,string[]>={qualifying:['qualifying'],race:['race'],sprintQualifying:['sprint qualifying','sprint shootout'],sprintRace:['sprint','sprint race']}
  const sameEvent=event&&session.meetingName.toLowerCase().replace(/grand prix|[^a-z0-9]/g,'')===event.meetingName.toLowerCase().replace(/grand prix|[^a-z0-9]/g,'')
  return <section className="page-view schedule-view"><div className="section-head"><div><small>RACE WEEKEND SCHEDULE · JST</small><h1>レースウィーク日程</h1></div><span>日本時間（Asia/Tokyo）</span></div><div className="weekend-picker" aria-label="グランプリを選択">{schedule.map(e=><button key={key(e)} aria-pressed={event&&key(event)===key(e)} onClick={()=>{setSelected(key(e));setNow(Date.now())}}><small>第{e.round}戦 {Date.parse(e.raceStart)>now?'開催予定':'開催済み'}</small><strong>{e.meetingName}</strong></button>)}</div>{event?<><h2>第{event.round}戦 {event.meetingName}</h2><p>{event.circuit} · {event.country}</p><div className="table-wrap"><table className="timing-table schedule-table"><thead><tr><th scope="col">日時（日本時間）</th><th scope="col">内容</th></tr></thead><tbody>{[...rows].sort((a,b)=>Date.parse(a.start??event.raceStart)-Date.parse(b.start??event.raceStart)).map(row=>{const active=sameEvent&&names[row.kind]?.includes(session.sessionName.toLowerCase()),status=!row.start?'時刻未発表':active&&session.status==='STARTED'?'開催中':active&&session.status==='ABORTED'?'中断中':active&&session.status==='FINISHED'?'終了':Date.parse(row.start)>now?'開始前':'開始時刻経過';return <tr key={row.kind+row.name}><td>{row.start?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(row.start)):'未発表'}</td><td><span className="driver-status">{status}</span> {row.kind==='practice'?<strong>{row.name}</strong>:<button className="schedule-session" onClick={()=>onSelectSession(row.kind as View)}>{row.name}</button>}</td></tr>})}</tbody></table></div></>:<p>日程を取得しています。</p>}</section>
}
